import { Department } from "../user/user.interface"

export enum RecognitionStatus {
   FAILED = "FAILED",
   SENT = "SENT"
}

export enum RecognitionValues {
  EXCEEDING_EXPECTATION = "EXCEEDING_EXPECTATION",
  RESULT_DRIVER = "RESULT_DRIVER",
  QUALITY_CHAMPION = "QUALITY_CHAMPION",
  OPERATIONAL_EXCELLENCE = "OPERATIONAL_EXCELLENCE",
  ACCOUNTABILITY_AND_OWNERSHIP = "ACCOUNTABILITY_AND_OWNERSHIP",
  DEPENDABILITY = "DEPENDABILITY",
  INNOVATION_CATALYST = "INNOVATION_CATALYST",
  CREATIVE_THINKING = "CREATIVE_THINKING",
  PROBLEM_SOLVER = "PROBLEM_SOLVER",
  ADAPTABILITY = "ADAPTABILITY",
  TEAM_PLAYER = "TEAM_PLAYER",
  CROSS_TEAM_COLLABORATOR = "CROSS_TEAM_COLLABORATOR",
  SUPPORTIVE_PEER = "SUPPORTIVE_PEER",
  POSITIVITY_CHAMPION = "POSITIVITY_CHAMPION",
  EMPOWERING_LEADER = "EMPOWERING_LEADER",
  INSPIRING_MENTOR = "INSPIRING_MENTOR",
  RISING_STAR = "RISING_STAR",
  ROLE_MODEL = "ROLE_MODEL",
  INTEGRITY_IN_ACTION = "INTEGRITY_IN_ACTION",
  CUSTOMER_CHAMPION = "CUSTOMER_CHAMPION"
}
export enum Category {
  PEER_TO_PEER_RECOGNITION = "SALES",
  EVERYDAY_APPRECIATION = "MARKETING",
  THANK_YOU_NOTE = "FINANCE_AND_MARKETING",
  EMPLOYEE_ACCOMPLISHMENTS = "OPERATIONS",
  EMERGING_LEADER_RECOGNITION = "HR",
  MANAGER_EXCELLENCE = "IT",
  EMPLOYEE_MILESTONES = "CUSTOMER_SERVICE",
  EMPLOYEE_WELCOME = "RESEARCH_AND_DEVELOPEMENT",
  SPECIAL_OCCASSIONS = "LEGAL_RISK_COMPLIANCE",
}
export enum Tone {
  PROFESSIONAL_AND_POLISHED = "SALES",
  WARM_AND_HEARTFELT = "MARKETING",
  ENERGETIC_AND_HYPE = "FINANCE_AND_MARKETING",
  APPRECIATIVE_SHORT_AND_SWEET = "OPERATIONS",
  WITTY_AND_FUN = "HR",
}


export interface IRecognition {
  senderEmail: string
  receiverEmail: string

  image:string
  department: Department
  category: Category
  tone: Tone
  value: RecognitionValues

  points: number
  message: string

  status: RecognitionStatus

  createdAt?: Date
  updatedAt?: Date
}